# Generated by Django 2.2.6 on 2019-10-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191014_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
            preserve_default=False,
        ),
    ]
