# Generated by Django 2.2.6 on 2019-10-14 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2014)]),
        ),
    ]
