# Generated by Django 2.2.6 on 2019-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191014_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
