# Generated by Django 2.2.6 on 2019-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191014_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
