# Generated by Django 2.2.6 on 2019-10-21 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191021_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2011, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2011)]),
        ),
    ]
