# Generated by Django 2.2.6 on 2019-10-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='desc',
        ),
    ]
