# Generated by Django 2.2.6 on 2019-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191027_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_end',
        ),
    ]
