# Generated by Django 2.2.6 on 2019-10-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_projectgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
            preserve_default=False,
        ),
    ]
