# Generated by Django 2.2.6 on 2019-10-27 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_id',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2011, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2011)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
