# Generated by Django 2.2.6 on 2019-10-27 21:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191027_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[app.models.validate_suponly_email], verbose_name='email address'),
        ),
    ]
